<a href="https://colab.research.google.com/github/SolMile/SolMile/blob/main/NUMPY_Solange.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *Milena Solange Andi Campos *
#NumPy Exercises for Data Analysis
#Ejercicios NumPy para el análisis de datos

1. Importar numpy como np y ver la versión tu código aquí
pasa

In [1]:
# 1. Import numpy as np and see the version
# your code here
!python --version
import numpy as np



Python 3.10.12


2. Crea un array 1D de números del 0 al 9



In [4]:
# 2. Create a 1D array of numbers from 0 to 9
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)
print(a.shape)
print(type(a))
print('1 dimesion :',a[1])

[0 1 2 3 4 5 6 7 8 9]
(10,)
<class 'numpy.ndarray'>
1 dimesion : 1


3. Create a 3×3 numpy array of all True’s



In [51]:
b =np.array([[7, 8, 9], [4, 5, 6], [7, 8, 9]])
print(b)

[[7 8 9]
 [4 5 6]
 [7 8 9]]


In [52]:
# 3. Create a 3×3 numpy array of all True’s
# your code here

mask =b>2
print(b.shape )
print(mask)
print(type(mask))

(3, 3)
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'>


4. Extraer todos los números impares del arr

In [53]:
# 4. Extract all odd numbers from arr
# your code here
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

imp = [x for x in arr if x % 2 != 0]
print(imp)


[1, 3, 5, 7, 9]


5. Reemplaza todos los números impares de arr por -1

In [54]:
# 5. Replace all odd numbers in arr with -1
# your code here
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for i in range(len(arr)):
    if arr[i] % 2 != 0:  # Verifica si el número es impar
        arr[i] = -1

print(arr)

[-1, 2, -1, 4, -1, 6, -1, 8, -1, 10]


6. Convertir un array 1D en un array 2D con 2 filas


In [55]:
 #  6. Convert a 1D array to a 2D array with 2 rows
# your code here

array_1dime = np.array([1, 2, 3, 4, 5, 6])

array_2dime = np.reshape(array_1dime, (2, -1))

print(array_2dime)

[[1 2 3]
 [4 5 6]]


7. Apila las matrices a y b verticalmente tu código aquí

In [56]:
#  7. Stack arrays a and b vertically
# your code here

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

stacked = np.vstack((a, b))

print(stacked)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


8. Apila las matrices a y b horizontalmente.

In [57]:
#  8. Stack the arrays a and b horizontally.
# your code here
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

stacked = np.hstack((a, b))

print(stacked)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


9. Obtén todos los elementos entre 5 y 10 de a.

In [64]:
#  9. Get all items between 5 and 10 from a.
# your code here
a = np.arange(15)

ele= a[5:11]
print(ele)

[ 5  6  7  8  9 10]


10. ¿Cómo hacer que una función python que maneja escalares funcione con arrays numpy?
Sugerencia
Salida deseada:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])


In [59]:
def pair_max(x, y):
    """Obtiene el máximo de dos elementos en arrays NumPy"""
    return np.maximum(x, y)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


11. Intercambia las columnas 1 y 2 del array arr.

In [65]:
arr = np.arange(9).reshape(3, 3)
print(arr)

# Intercambiar columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


12. Crear un array 2D de forma 5x3 para contener números decimales aleatorios entre 5

In [66]:
# Crear un array 2D de forma 5x3 con números decimales aleatorios entre 5 y 10
arr = np.random.uniform(5, 10, (5, 3))

print(arr)

[[6.23803792 5.8941851  7.12139162]
 [8.35370416 5.22321641 6.348545  ]
 [9.83793395 6.80463904 7.09347392]
 [7.7041318  5.96794615 7.91882432]
 [5.94854708 7.78775278 9.78940692]]
